version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=icu-connect
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U root -d icu-connect' ]
      interval: 5s
      timeout: 5s
      retries: 2
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql

  api:
    container_name: api
    image: icu-connect
    build:
      context: ./
      dockerfile: Dockerfile

    environment:
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_NAME: icu-connect
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/icu-connect?createDatabaseIfNotExist=true autoReconnect=true
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - 8080:8080
    restart: always

volumes:
  postgres:
