version: '3'
services:

  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Mocolococo1!
      - MYSQL_DATABASE=icu-connect
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=Mocolococo1!
    restart: always
    ports:
      - 3307:3306
    volumes:
      - mysqldb:/var/lib/mysql

  api:
    container_name: api
    image: icu-connect
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_PASSWORD: Mocolococo1!
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_NAME: icu-connect
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/icu-connect?createDatabaseIfNotExist=true&autoReconnect=true
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    restart: always

volumes:
  mysqldb:
